services:
- type: web
  name: ghost
  env: docker
  autoDeploy: false
  envVars:
    - key: database__client
      value: mysql
    - key: database__connection__host
      fromService:
        type: web
        name: ghost
        property: host
    - key: database__connection__database
      fromService:
        type: web
        name: ghost
        envVarKey: MYSQL_DB
    - key: database__connection__user
      fromService:
        type: web
        name: ghost
        envVarKey: MYSQL_USER
    - key: database__connection__password
      fromService:
        type: web
        name: ghost
        envVarKey: MYSQL_PASSWORD
